In [25]:
import os
import cv2
import numpy as np
from PIL import Image

face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')#学習データ

img_dir_path = input('画像フォルダのパスを入力してください：')#

#img_dir_path = '/Users/user/Desktop/drive-download'
pictures = os.listdir(img_dir_path)#フォルダリストの中身をリスト化

if '.DS_Store' in pictures:
    pictures.remove('.DS_Store')

if 'Thumbs.db' in pictures:
    pictures.remove('Thumbs.db')
    
print(pictures)

os.mkdir(os.path.join(img_dir_path,'output'))

i = 0

while i < len(pictures):

    img = cv2.imread(os.path.join(img_dir_path,pictures[i]))
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, scaleFactor = 1.2, minSize = (250,250), maxSize = (1600,1600))


#    for (x, y, w, h) in faces:
#        cv2.rectangle(img, (x, y), (x+w, y+h), (0, 0, 255))
#        resized_img = cv2.resize(img,(450, 300))
#        cv2.imshow("test.jpg", resized_img)
#        cv2.waitKey(0)
#        cv2.destroyAllWindows 
    print(pictures[i])
    print(faces)

#顔認証に失敗した場合
    if len(faces) == 0:
        img = cv2.imread(os.path.join(img_dir_path,pictures[i]))


# 回転角の指定
        for j in range(-15,15):#-４５°〜４５°まで画像を回転
            angle = 5*j
            scale = 1.0

            height, width = img.shape[:2]
#回転の中心を指定                          
            center = (int(width/2), int(height/2))
        
            trans = cv2.getRotationMatrix2D(center, angle , scale)
#アフィン変換
            img = cv2.warpAffine(img, trans, (width,height))
        
        
            gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
            faces = face_cascade.detectMultiScale(gray, scaleFactor = 1.2, minSize = (250,250), maxSize = (1600,1600))
            if len(faces) > 0:
                print('回転させた結果認識!' + str(faces))
                
                
                
                break
            
                
            
        
        
        
        
        #im_crop = img.crop((100, 200, 300, 400))
        #im_crop.save(os.path.join(img_dir_path,'output',pictures[i])+"【fail】.jpg", quality=100) #dpiも設定してください dpi=(300, 300))
        cv2.imwrite(os.path.join(img_dir_path,'output',pictures[i])+"【fail】.jpg", img)
    
#顔認証に成功した場合
    elif len(faces) > 0:
        face_max = faces[faces[:, 2].argmax()]

        print(face_max)

        img = Image.open(os.path.join(img_dir_path,pictures[i]))
        width, height = img.size

        print(face_max[0])

#クロップ位置の定義（顔を中心に正方形に切り取る）
        X1 = face_max[0]+0.5*face_max[2]-0.5*height
        Y1 = (face_max[1]+0.5*face_max[3]-0.5*width)*0.5#
        X2 = X1 + height
        Y2 = Y1 + width


#横写真だった場合の条件
        if X1 < 0:
            X1 = 0
            X2 = X1 + height
        
        if X2 > width:
            X2 = width
            X1 = X2 - height

        if Y1 < 0:
            Y1 = 0
            Y2 = Y1 + width

        if Y2 > height:
            Y2 = height
            Y1 = Y2 - width

        if width > height:#横写真の場合、以下のようにクロップ
            #im_crop = img.crop((X1, 0, X2, height))
            im_crop = img.crop((X1 + height*17.5/615, 0, X2 - height*17.5/615, height))
            im_resize = im_crop.resize((580,615))
            im_resize.save(os.path.join(img_dir_path,'output',pictures[i]), quality=100, dpi=(300, 300)) #dpiも設定してください dpi=(300, 300))
            
        elif width < height:#縦写真だった場合、
            im_crop = img.crop((0, Y1, width, Y2 + width*35/615))
            im_resize = im_crop.resize((580,615))
            im_resize.save(os.path.join(img_dir_path,'output',pictures[i]), quality=100, dpi=(300, 300)) #dpiも設定してください dpi=(300, 300))

    i = i + 1 

print('END')



画像フォルダのパスを入力してください：/Users/user/Downloads/3.キッズ
['2311097.jpg', '2311083.jpg', '2311068.jpg', '2311054.jpg', '2311108.jpg', '2311120.jpg', '2311134.jpg', '2311135.jpg', '2311121.jpg', '2311109.jpg', '2311055.jpg', '2311069.jpg', '2311082.jpg', '2311096.jpg', '2311080.jpg', '2311094.jpg', '2311057.jpg', '2311137.jpg', '2311123.jpg', '2311122.jpg', '2311136.jpg', '2311056.jpg', '2311095.jpg', '2311081.jpg', '2311085.jpg', '2311091.jpg', '2311052.jpg', '2311132.jpg', '2311126.jpg', '2311127.jpg', '2311133.jpg', '2311053.jpg', '2311090.jpg', '2311084.jpg', '2311092.jpg', '2311086.jpg', '2311051.jpg', '2311079.jpg', '2311125.jpg', '2311131.jpg', '2311119.jpg', '2311118.jpg', '2311130.jpg', '2311124.jpg', '2311078.jpg', '2311087.jpg', '2311093.jpg', '2311180.jpg', '2311194.jpg', '2311143.jpg', '2311157.jpg', '2311156.jpg', '2311142.jpg', '2311195.jpg', '2311181.jpg', '2311197.jpg', '2311183.jpg', '2311168.jpg', '2311154.jpg', '2311140.jpg', '2311141.jpg', '2311155.jpg', '2311169.jpg', '23111

2311148.jpg
[[894 982 659 659]]
[894 982 659 659]
894
2311170.jpg
[[1262  431  813  813]]
[1262  431  813  813]
1262
2311164.jpg
[[976 871 820 820]]
[976 871 820 820]
976
2311158.jpg
[[ 891 1108  908  908]]
[ 891 1108  908  908]
891
2311159.jpg
[[1695  530 1060 1060]
 [1320 1830  532  532]]
[1695  530 1060 1060]
1695
2311165.jpg
[[1085  385  962  962]]
[1085  385  962  962]
1085
2311171.jpg
()
回転させた結果認識![[ 842 1094  589  589]]
2311198.jpg
[[1004  409  436  436]]
[1004  409  436  436]
1004
2311167.jpg
[[1181  501  372  372]]
[1181  501  372  372]
1181
2311173.jpg
[[ 709 1051  828  828]]
[ 709 1051  828  828]
709
2311172.jpg
[[ 925  909 1265 1265]]
[ 925  909 1265 1265]
925
2311166.jpg
[[1496  899  913  913]]
[1496  899  913  913]
1496
2311199.jpg
[[657 958 994 994]]
[657 958 994 994]
657
2311075.jpg
[[ 722  556 1537 1537]]
[ 722  556 1537 1537]
722
2311061.jpg
()
回転させた結果認識![[651 833 844 844]]
2311129.jpg
[[935 557 773 773]]
[935 557 773 773]
935
2311101.jpg
[[ 649  810 1020 1020]]
[ 649